id = "selene-abyss-theme"
name = "Selene Abyss"
version = "0.0.3"
schema_version = 1
authors = ["envoidia"]
description = "A blue and purple-focused dark theme"
repository = "https://github.com/envoidia/zed-selene-abyss"
